from fastapi import APIRouter, Depends, Query
from fastapi.responses import RedirectResponse, HTMLResponse
from controllers.google_oauth_controller import GoogleOAuthController
from core.middleware import get_current_user

router = APIRouter(prefix="/oauth", tags=["OAuth"])

@router.get("/google/authorize")
async def initiate_google_oauth(
    current_user: dict = Depends(get_current_user)
):
    """Initiate Google OAuth flow for Drive access"""
    import os
    
    # Get backend URL for callback
    # Uses env var in prod, defaults to localhost in dev
    backend_url = os.getenv("BACKEND_URL", "http://localhost:8000")
            
    redirect_uri = f"{backend_url}/oauth/google/callback"
    
    result = await GoogleOAuthController.initiate_oauth(
        user_id=str(current_user["_id"]),
        redirect_uri=redirect_uri
    )
    return RedirectResponse(url=result["oauth_url"])

@router.get("/google/callback")
async def google_oauth_callback(
    code: str = Query(...),
    state: str = Query(...)
):
    """Handle Google OAuth callback for Drive access"""
    import os
    
    # Get backend URL for callback (prod) or default to localhost (dev)
    backend_url = os.getenv("BACKEND_URL", "http://localhost:8000")
            
    redirect_uri = f"{backend_url}/oauth/google/callback"
    
    result = await GoogleOAuthController.handle_callback(code=code, state=state, redirect_uri=redirect_uri)
    
    # Redirect to frontend
    frontend_url = os.getenv("FRONTEND_URL")
    if frontend_url:
        return RedirectResponse(url=f"{frontend_url}/mcp-servers?google_auth=success")
    else:
        return {"status": "success", "message": "Google Drive connected successfully (Backend Only Mode)"}

@router.get("/mcp/callback")
async def mcp_oauth_callback(
    code: str = Query(...),
    state: str = Query(...)
):
    """OAuth 2.1 callback for MCP servers. The third party redirects the user's
    browser here; we don't need to know who the user is — the `state` value
    (generated by the MCP SDK's OAuthClientProvider) correlates this callback
    back to the pending authorization flow via Redis. See
    utils/mcp_oauth_flow.py."""
    from utils.mcp_oauth_flow import deliver_callback

    delivered = await deliver_callback(code=code, state=state)

    import os
    frontend_url = os.getenv("FRONTEND_URL")
    if delivered:
        if frontend_url:
            return RedirectResponse(url=f"{frontend_url}/mcp-servers?mcp_oauth=success")
        return HTMLResponse("<html><body>Authorization received — you can close this tab.</body></html>")

    if frontend_url:
        return RedirectResponse(url=f"{frontend_url}/mcp-servers?mcp_oauth=expired")
    return HTMLResponse(
        "<html><body>This authorization link has expired or is unknown. "
        "Please restart the connection from Settings &gt; MCP Servers.</body></html>",
        status_code=400,
    )

@router.get("/google/status")
async def get_google_oauth_status(
    current_user: dict = Depends(get_current_user)
):
    """Check if user has connected Google Drive"""
    from core.database import oauth_tokens_collection
    
    token_doc = await oauth_tokens_collection.find_one({
        "user_id": str(current_user["_id"]),
        "provider": "google"
    })
    
    if token_doc:
        # Get email from token doc if stored, otherwise return generic response
        return {
            "connected": True,
            "email": token_doc.get("email", "Connected")
        }
    else:
        return {"connected": False}

@router.post("/google/disconnect")
async def disconnect_google_oauth(
    current_user: dict = Depends(get_current_user)
):
    """Disconnect Google Drive by deleting stored credentials"""
    from core.database import oauth_tokens_collection
    
    result = await oauth_tokens_collection.delete_one({
        "user_id": str(current_user["_id"]),
        "provider": "google"
    })
    
    if result.deleted_count > 0:
        return {"success": True, "message": "Google Drive disconnected"}
    else:
        return {"success": False, "message": "No connection found"}
