from typing import List, TypedDict, Optional
from langchain_core.documents import Document
from langchain_core.messages import BaseMessage

class RAGGraphState(TypedDict):
    """
    Represents the state of the Agentic RAG Graph.
    Implements the "State" for the cyclical flow defined in Architecture v11.1.
    """
    
    question: str
    """The user's original question."""
    
    documents: List[Document]
    """List of documents retrieved from Vector Store or Web."""
    
    generation: Optional[str]
    """The answer generated by the LLM."""
    
    web_search_needed: bool
    """Flag to indicate if internal knowledge was insufficient."""
    
    hallucination_count: int
    """Counter to prevent infinite verification loops."""
    
    retry_count: int
    """Counter for general retries (guardrail < 3)."""

    selected_files: Optional[List[str]]
    """List of file IDs/Names to filter search context."""

    messages: List[BaseMessage]
    """Agent scratchpad / conversation history."""
